# Site settings
baseurl = "https://interstellar.flights/"
languageCode = "ko-kr"
title = "Interstellar Relay Community"
theme = "andromeda"

[params]
  [params.header]
    title = "Interstellar Relay Community"
    description = "이어지고 싶은 사람들을 위한 공동체"
    image = "images/logo.svg"

  [params.title]
    title = "High Performance ActivityPub Relay"
    subtitle = "고성능 ActivityPub 중계 서비스"

  [params.footer]
    enable = false
    title = "Aliquam sed mauris"
    description = "Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio."
    email = "information@untitled.tld"

  [params.footer.copyright]
    enable = true
    text = "© Interstellar Relay Community"
    author = "Rhahi"
    link = ""
