# Site settings
baseurl = "https://interstellar.flights/"
languageCode = "ko-kr"
title = "Interstellar Relay Community"
theme = "andromeda"

[params]
  [params.header]
    title = "Interstellar Relay Community"
    short = "I.R.C."
    description = "이어지고 싶은 사람들을 위한 공동체"
    image = "images/logo.svg"

  [params.title]
    title = "High Performance ActivityPub Relay"
    subtitle = "고성능 ActivityPub 중계 서비스"

  [params.footer.copyright]
    enable = true
    text = "© Interstellar Relay Community"
    linkname = "GitHub"
    link = "https://github.com/Interstellar-Relay-Community/landing"
