# Site settings
baseurl = "https://interstellar.flights/"
languageCode = "ko-kr"
title = "Interstellar Relay Community"
theme = "stellar"

googleAnalytics = "" #put your google-analytics ID here

[params]
  [params.header]
    title = "Interstellar Relay Community"
    description = '이어지고 싶은 사람들을 위한 공동체'
    image = "images/logo.svg"

  [[params.navigation]]
    name = "소개"
    href = "#intro"

  [[params.navigation]]
    name = "특징"
    href = "#speciality"

  [[params.navigation]]
    name = "릴레이 서비스"
    href = "#relay-svc"

  [[params.navigation]]
    name = "문의사항"
    href = "#contacts"

  [params.intro]
    title = "소개"
    description = "Interstellar Relay Community는 ActivityPub 프로토콜을 사용하는 서비스 간 메세지를 중계하는 릴레이 서비스 입니다."

  [[params.section]]
    id = "speciality"
    title = "특징"
    description = "Interstellar Relay Community 는 다른 릴레이에 비해 아래와 같은 차별점을 가집니다."

    [params.section.features]
      enable = true
      [[params.section.feature]]
        title = "높은 성능"
        description = "Rust 기반의 코드로 작성되어 타 릴레이 구현체 대비 적은 오버헤드로 더욱 높은 성능을 자랑합니다."
        icon = "fa-code"

      [[params.section.feature]]
        title = "우수한 안정성"
        description = "검증된 설비 상에서 운용되는 릴레이 구현체 자체의 안정성과 더불어 경험이 풍부한 관리 인원의 지원에 힘입어 더욱 우수한 안정성을 자랑합니다."
        icon = "fa-server"

  [[params.section]]
    id = "relay-svc"
    title = "릴레이 서비스"
    description = "Interstellar Relay Community 는 다음과 같은 서비스를 운용 중입니다."
    [params.section.content]
      enable = true
      text = "* ActivityPub 릴레이 [https://ap.interstellar.flights](https://ap.interstellar.flights/)"


  [[params.section]]
    id = "contacts"
    title = "문의사항"
    description = "릴레이에 참여하시고 싶으시거나 문의 사항이 있으시다면 아래의 폼을 이용해 연락해주세요."
    [params.section.footer]
      enable = true
      [[params.section.footer.action]]
        buttontext = "참여하기"
        buttonUrl = "https://forms.gle/BT9zBH8B3uUpzY1W6"
        customClass = "special"

  [params.footer]
    enable = false
    title = "Aliquam sed mauris"
    description = "Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio."

    second_title = "Etiam feugiat"
    address = "1234 Somewhere Road &bull; Nashville, TN 00000 &bull; USA"
    phone = "(000) 000-0000 x 0000"
    email = "information@untitled.tld"

    [[params.footer.action]]
      href = "generic.html"
      buttontext = "Learn More"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "GitHub"
        icon = "fa-github"
        link = "https://github.com/Interstellar-Relay-Community"

      #[[params.footer.social]]
      #  title = "Facebook"
      #  icon = "fa-facebook"
      #  link = "#"

      #[[params.footer.social]]
      #  title = "Instagramm"
      #  icon = "fa-instagram"
      #  link = "#"

      #[[params.footer.social]]
      #  title = "Dribbble"
      #  icon = "fa-dribbble"
      #  link = "#"

      #[[params.footer.social]]
      #  title = "Email"
      #  icon = "fa-envelope"
      #  link = "#"

    # copyright
    [params.footer.copyright]
      enable = true
      text = "© Interstellar Relay Community, Design: [HTML5UP](//html5up.net)"
