name = "Andromeda"
license = "MIT"
licenselink = "https://github.com/Interstellar-Relay-Community/landing/blob/master/themes/andromeda/LICENSE"
description = "Theme designed for Interstellar Relay Community's landing page."
homepage = "https://interstellar.flights/"
min_version = "0.41.0"
tags = ["company"]
features = []

[author]
  name = "Rhahi"
  homepage = "https://github.com/Interstellar-Relay-Community/landing"
